ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO todo_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO todo_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO todo_app;
